POST http://localhost:8080/competitor
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name":"Eduardo Alfonso Sanchez",
  "username": "ealfonso@gmail.com",
  "password": "Password01",
  "avatar": "Dracula",
  "weight": 15.32,
  "height": 13.2,
  "gender": "M",
  "dateBirth": "1985-11-11",
  "cityId": 2,
  "address": "Apto 2 B43 Distrito Jose Marti",
  "facebook": "eddie.alfonso1"
}

###