spring:
  profiles.active: develop
---
spring:
  profiles: develop
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: SA
    password:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      pool-name: H2-POOL
---
spring:
  profiles: develop
  datasource:
   type: com.zaxxer.hikari.HikariDataSource
   url: jdbc:mysql://localhost/sportgift_db?useSSL=false
   username: root
   password: root
   hikari:
    connection-timeout: 60000
    maximum-pool-size: 20
    idle-timeout: 600000
    max-lifetime: 1800000
    connection-test-query: SELECT 1
    pool-name: MYSQL-POOL
---
logging:
  level:
    sql: debug
    ROOT: info
server:
  port: 8080